// Fast Square Root
native Float:c_fast_square_root(Float:number);

// Square Root (Prefer using c_fast_square_root)
native Float:c_square_root(Float:number);

// Clamp
native Float:c_clamp(Float:number1, Float:number2, Float:number3);

// Clamp Int
native c_clamp_int(number1, number2, number3);

// Max
native Float:c_max(Float:number1, Float:number2);

// Max Int
native c_max_int(number1, number2);

// Min
native Float:c_min(Float:number1, Float:number2);

// Min Int
native c_min_int(number1, number2);

// Multiply
native Float:c_multiply(Float:number1, Float:number2);

// Multiply Int
native c_multiply_int(number1, number2);

// Add
native Float:c_add(Float:number1, Float:number2);

// Add Int
native c_add_int(number1, number2);

// Subtract
native Float:c_subtract(Float:number1, Float:number2);

// Subtract Int
native c_subtract_int(number1, number2);

// Divide
native Float:c_divide(Float:num1, Float:number2);

// Divide Int
native c_divide_int(number1, number2);